server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/springec_manage
    username: root
    password: "0731"
    driver-class-name: org.mariadb.jdbc.Driver