server:
  port: 8082
  servlet:
    context-path: /restfulapi
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/springec_database
    username: root
    password: "0731"
    driver-class-name: org.mariadb.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: false
